name: Bug Report
description: Report a bug in an Error Explorer SDK
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: sdk
    attributes:
      label: SDK
      description: Which SDK is affected?
      options:
        - "@error-explorer/browser"
        - "@error-explorer/node"
        - "@error-explorer/react"
        - "@error-explorer/vue"
        - "error-explorer/php-sdk"
        - "error-explorer/symfony-sdk"
        - "error-explorer/laravel-sdk"
        - "error-explorer (Python)"
        - "error-explorer-django"
        - "error-explorer-flask"
        - "error-explorer-fastapi"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Initialize SDK with '...'
        2. Trigger error '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment info:
        - OS: [e.g., macOS 14, Ubuntu 22.04]
        - Runtime: [e.g., Node 20, PHP 8.2, Python 3.12]
        - Framework version: [e.g., React 18, Symfony 7, Django 5]
      placeholder: |
        - OS:
        - Runtime:
        - Framework:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output.
      render: shell
